# Generated by Django 5.2.1 on 2025-05-20 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=100, verbose_name='Maxsalat turi (UZ)')),
                ('name_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='Maxsalat turi (RU)')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Maxsalat turi (EN)')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Maxsalat turi slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqti")),
            ],
            options={
                'verbose_name': 'Maxsalat turi',
                'verbose_name_plural': 'Maxsalat turlari',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='To‘liq ismi')),
                ('email', models.EmailField(max_length=254, verbose_name='Email manzil')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqam')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Buyurtma vaqti')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=100, verbose_name='Maxsalat nomi (UZ)')),
                ('name_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='Maxsalat nomi (RU)')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Maxsalat nomi (EN)')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Maxsalat nomi slug')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Maxsalat haqida (UZ)')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Maxsalat haqida (RU)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Maxsalat haqida (EN)')),
                ('ingredients_uz', models.TextField(blank=True, null=True, verbose_name='Maxsalat tarkibi (UZ)')),
                ('ingredients_ru', models.TextField(blank=True, null=True, verbose_name='Maxsalat tarkibi (RU)')),
                ('ingredients_en', models.TextField(blank=True, null=True, verbose_name='Maxsalat tarkibi (EN)')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maxsalat narxi')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maxsalat chegirmali narxi')),
                ('stock', models.IntegerField(blank=True, null=True, verbose_name='Maxsalat miqdori')),
                ('available', models.BooleanField(default=True, verbose_name='Maxsalat mavjudligi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Maxsalat rasmi')),
                ('files', models.FileField(blank=True, null=True, upload_to='products/files/', verbose_name='Maxsalat fayli')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqti")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savdo.category', verbose_name='Maxsalat turi')),
            ],
            options={
                'verbose_name': 'Maxsalat',
                'verbose_name_plural': 'Maxsalatlar',
            },
        ),
    ]
