# Generated by Django 5.2.1 on 2025-05-17 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Maxsalat turi')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Maxsalat turi slug')),
                ('description', models.TextField(verbose_name='Maxsalat turi haqida')),
                ('image', models.ImageField(upload_to='categories/', verbose_name='Maxsalat turi rasmi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
            ],
            options={
                'verbose_name': 'Maxsalat turi',
                'verbose_name_plural': 'Maxsalat turlari',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Maxsalat nomi')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Maxsalat nomi slug')),
                ('description', models.TextField(verbose_name='Maxsalat haqida')),
                ('ingredients', models.TextField(verbose_name='Maxsalat tarkibi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Maxsalat narxi')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maxsalat chegirmali narxi')),
                ('stock', models.IntegerField(verbose_name='Maxsalat miqdori')),
                ('available', models.BooleanField(default=True, verbose_name='Maxsalat mavjudligi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Maxsalat rasmi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savdo.category', verbose_name='Maxsalat turi')),
            ],
            options={
                'verbose_name': 'Maxsalat',
                'verbose_name_plural': 'Maxsalatlar',
            },
        ),
    ]
