# Generated by Django 5.2.1 on 2025-05-17 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savdo', '0002_category_updated_at_alter_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='To‘liq ismi')),
                ('email', models.EmailField(max_length=254, verbose_name='Email manzil')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqam')),
                ('city', models.CharField(max_length=100, verbose_name='Shahar')),
                ('district', models.CharField(max_length=100, verbose_name='Tuman')),
                ('street', models.CharField(max_length=100, verbose_name='Ko‘cha')),
                ('house_number', models.CharField(max_length=100, verbose_name='Uy raqami')),
                ('apartment_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Xonadon raqami')),
                ('address', models.TextField(verbose_name='Manzil')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Jami narx')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Buyurtma vaqti')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Soni')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narxi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqti")),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='savdo.order', verbose_name='Buyurtma')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savdo.product', verbose_name='Maxsulot')),
            ],
            options={
                'verbose_name': 'Buyurtma mahsuloti',
                'verbose_name_plural': 'Buyurtma mahsulotlari',
            },
        ),
    ]
