# Generated by Django 5.2.1 on 2025-05-27 10:24

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savdo', '0003_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ingredients_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ingredients_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ingredients_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='English sarlovha umumiy matini'),
        ),
        migrations.AddField(
            model_name='product',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Ruscha sarlovha umumiy matini'),
        ),
        migrations.AddField(
            model_name='product',
            name='content_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Sarlovha umumiy matini'),
        ),
    ]
