# Generated by Django 5.2.1 on 2025-05-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savdo', '0004_remove_product_discount_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='all_files',
            field=models.FileField(blank=True, null=True, upload_to='products/files/', verbose_name='Umumiy maxsalatlar fayli'),
        ),
    ]
