# Generated by Django 5.2.1 on 2025-05-29 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savdo', '0006_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='all_files',
        ),
    ]
