# Generated by Django 5.2.1 on 2026-02-13 04:46

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savdo', '0007_remove_product_all_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Yangilik matni (EN)'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Yangilik matni (RU)'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Yangilik matni (UZ)'),
        ),
    ]
